web:
  build: .
  command: ./gradlew fC fM build run
  ports:
    - "8088:8088"
  links:
    - db
    - redis
  volumes:
    - .:/myapp

db:
  image: mysql:5.6
  environment:
    MYSQL_DATABASE: ke_tsu
    MYSQL_USER: mysql
    MYSQL_PASSWORD: mysql
    MYSQL_ROOT_PASSWORD: mysql
  ports:
    - "3306:3306"

redis:
  image: hpess/redis
  hostname: 'redis'
  environment:
    redis_mode: 'both'
    master_name: 'redis'
